# Generated by Django 3.2.5 on 2021-08-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='libros',
            field=models.ManyToManyField(related_name='autores', to='app.Libro'),
        ),
    ]
