# Generated by Django 3.2.5 on 2021-08-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_autor_libros'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='notas',
            field=models.CharField(default='Sin Notas', max_length=255),
            preserve_default=False,
        ),
    ]
